sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t pedrobralv/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pedrobralv/docker-react npm run test